### ISSUE TITLE
release?

### ISSUE THREAD

**Issue by ghost** [DavidMoore/PinWindows#1]
this sounds pretty useful, have you ever thought about making a release?

**Comment by DavidMoore** [comment]
Sure I can do that.

There is also a new Windows PowerToys that does this and more if you were interested: https://learn.microsoft.com/en-us/windows/powertoys/always-on-top

**Comment by DavidMoore** [comment]
Ok I made a release; let me know if it can't launch for you as it's just a self-contained .exe for now.

**Comment by ghost** [comment]
> Ok I made a release; let me know if it can't launch for you as it's just a self-contained .exe for now.

seems to be working as intended.  that's pretty neat for a 47KB program. I have only one issue: it doesn't want to untick the "start when windows starts" option.

**Comment by ghost** [comment]
it also doesn't seem to recognize Explorer. other than that, it's working fine

**Comment by DavidMoore** [comment]
Oh that untick option isn't working because of a dumb bug by the looks which I can fix.

Windows Explorer doesn't seem to show its window titles, so PinWindows filters it out. I might have to figure out how to get the Explorer window details.

You're not using Windows 11 like I are you? Do you also use Explorer tabs?

**Comment by ghost** [comment]
I'm using windows 10
